#!/usr/bin/env python3
"""
Organizes files into directories w.r.t there extensions.
"""
import os
import shutil
import sys


def is_not_hidden(test_file):
    if test_file.startswith('.'):
        return False
    return True


def organize_files(unorganized_path, destination):
    if not os.path.exists(unorganized_path):
        raise FileNotFoundError("The Source path doesn't exist.")
    if not os.path.exists(destination):
        raise FileNotFoundError("The Destination path doesn't exist.")
    for filename in os.listdir(unorganized_path):
        file_path = os.path.join(unorganized_path, filename)
        if os.path.isfile(file_path) and is_not_hidden(filename) and '.' in filename:
            foldername = filename.split('.')[1]
            dest_folder_path = os.path.join(destination, foldername)
            print(end='') if os.path.exists(dest_folder_path) else os.mkdir(dest_folder_path)
            shutil.move(file_path, os.path.join(dest_folder_path, filename))

            
if __name__ == '__main__':
    if len(sys.argv) == 3:
        source_path = sys.argv[1]
        destination_path = sys.argv[2]
    elif len(sys.argv) == 1:
        source_path = input("Source Folder Path: ")
        destination_path = input("Destination Folder Path: ")
    else:
        raise Exception("The arguments passed were wrong.")
    organize_files(source_path, destination_path)
    print("Your files were organized at \"{}\"".format(os.path.abspath(destination_path)))
